### ISSUE TITLE
Error running npm run build

### ISSUE THREAD

**Issue by gibbster** [aws-samples/amazon-eks-refarch-cloudformation#14]
Hello there,

I'm getting the following error message when trying to run the build script. Any suggestions would be welcome!

> tsc

node_modules/@types/node/index.d.ts:97:11 - error TS2300: Duplicate identifier 'IteratorResult'.

97 interface IteratorResult<T> { }
             ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6
    41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
            ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  node_modules/@types/node/index.d.ts:97:11
    97 interface IteratorResult<T> { }
                 ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.

Found 2 errors.

**Comment by pahud** [comment]
Hi

I've refreshed the CDK sample and you don't have to run `cdk build` before `cdk deploy` anymore.

Please `git pull` to udpate the repo, go to the `cdk` sub-directory under the project root, delete all `node_modules`, and `npm install` again then follow the README to complete your cdk deployment. It should work. 


https://github.com/aws-samples/amazon-eks-refarch-cloudformation/tree/master/cdk
